version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: monthly
    commit-message:
      prefix: "[cargo]"
    groups:
      deps:
        patterns:
          - "*"
    labels:
      - dependencies
      - d:cargo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[gh-actions]"
    labels:
      - dependencies
      - d:github-actions
