[package]
name = "rsrepo"
version = "0.1.0"
edition = "2021"
description = "Rust project templater & releaser"
authors = ["John Thorvald Wodder II <rsrepo@varonathe.org>"]
repository = "https://github.com/jwodder/rsrepo"
documentation = "https://github.com/jwodder/rsrepo"
license = "MIT"
exclude = ["/.*"]

[dependencies]
anyhow = "1.0.71"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.2.7", default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
fern = "0.6.2"
home = "0.5.5"
include_dir = "0.7.3"
log = "0.4.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
shell-words = "1.1.0"
tera = { version = "1.18.1", default-features = false }
thiserror = "1.0.40"
toml = { version = "0.7.3", default-features = false, features = ["parse"] }

[dev-dependencies]
assert_cmd = "2.0.11"
similar = "2.2.1"
tempdir = "0.3.7"
tempfile = "3.5.0"

[profile.release]
lto = true
strip = true
