[package]
name = "rsrepo"
version = "0.1.0"
edition = "2021"
description = "Rust project templater & releaser"
authors = ["John Thorvald Wodder II <rsrepo@varonathe.org>"]
repository = "https://github.com/jwodder/rsrepo"
documentation = "https://github.com/jwodder/rsrepo"
keywords = ["cargo", "template-project"]
license = "MIT"
exclude = ["/.*"]
publish = false

[dependencies]
anstream = "0.3.2"
anstyle = "1.0.0"
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.2.7", default-features = false, features = ["derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
fern = "0.6.2"
gh-token = "0.1.1"
ghrepo = { version = "0.5.0", default-features = false }
home = "0.5.5"
include_dir = "0.7.3"
indent_write = "2.2.0"
log = "0.4.17"
mime = "0.3.17"
nom = "7.1.3"
parse_link_header = "0.3.3"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
shell-words = "1.1.0"
thiserror = "1.0.40"
tinytemplate = "1.2.1"
toml = { version = "0.7.3", default-features = false, features = ["parse"] }
ureq = { version = "2.6.2", features = ["json"] }
url = "2.3.1"
which = "4.4.0"

[dev-dependencies]
assert_cmd = "2.0.11"
rstest = { version = "0.17.0", default-features = false }
similar = "2.2.1"
tempfile = "3.5.0"

[profile.release]
lto = true
strip = true
