[package]
name = "rsrepo"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
log = "0.4.17"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
shell-words = "1.1.0"
thiserror = "1.0.40"
